# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffer_ddf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ddf_extensions_pb2 as ddf__extensions__pb2
import ddf_math_pb2 as ddf__math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buffer_ddf.proto',
  package='dmBufferDDF',
  syntax='proto2',
  serialized_options=_b('\n\030com.dynamo.gamesys.protoB\013BufferProto'),
  serialized_pb=_b('\n\x10\x62uffer_ddf.proto\x12\x0b\x64mBufferDDF\x1a\x14\x64\x64\x66_extensions.proto\x1a\x0e\x64\x64\x66_math.proto\"\xab\x01\n\nStreamDesc\x12\x0c\n\x04name\x18\x01 \x02(\t\x12*\n\nvalue_type\x18\x02 \x02(\x0e\x32\x16.dmBufferDDF.ValueType\x12\x13\n\x0bvalue_count\x18\x03 \x02(\r\x12\n\n\x02ui\x18\x04 \x03(\r\x12\t\n\x01i\x18\x05 \x03(\x05\x12\x0c\n\x04ui64\x18\x06 \x03(\x04\x12\x0b\n\x03i64\x18\x07 \x03(\x03\x12\t\n\x01\x66\x18\x08 \x03(\x02\x12\x11\n\tname_hash\x18\t \x02(\x04\"6\n\nBufferDesc\x12(\n\x07streams\x18\x01 \x03(\x0b\x32\x17.dmBufferDDF.StreamDesc*\xd5\x01\n\tValueType\x12\x14\n\x10VALUE_TYPE_UINT8\x10\x00\x12\x15\n\x11VALUE_TYPE_UINT16\x10\x01\x12\x15\n\x11VALUE_TYPE_UINT32\x10\x02\x12\x15\n\x11VALUE_TYPE_UINT64\x10\x03\x12\x13\n\x0fVALUE_TYPE_INT8\x10\x04\x12\x14\n\x10VALUE_TYPE_INT16\x10\x05\x12\x14\n\x10VALUE_TYPE_INT32\x10\x06\x12\x14\n\x10VALUE_TYPE_INT64\x10\x07\x12\x16\n\x12VALUE_TYPE_FLOAT32\x10\x08\x42\'\n\x18\x63om.dynamo.gamesys.protoB\x0b\x42ufferProto')
  ,
  dependencies=[ddf__extensions__pb2.DESCRIPTOR,ddf__math__pb2.DESCRIPTOR,])

_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='dmBufferDDF.ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_UINT8', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_UINT16', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_UINT32', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_UINT64', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_INT8', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_INT16', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_INT32', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_INT64', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_TYPE_FLOAT32', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=302,
  serialized_end=515,
)
_sym_db.RegisterEnumDescriptor(_VALUETYPE)

ValueType = enum_type_wrapper.EnumTypeWrapper(_VALUETYPE)
VALUE_TYPE_UINT8 = 0
VALUE_TYPE_UINT16 = 1
VALUE_TYPE_UINT32 = 2
VALUE_TYPE_UINT64 = 3
VALUE_TYPE_INT8 = 4
VALUE_TYPE_INT16 = 5
VALUE_TYPE_INT32 = 6
VALUE_TYPE_INT64 = 7
VALUE_TYPE_FLOAT32 = 8



_STREAMDESC = _descriptor.Descriptor(
  name='StreamDesc',
  full_name='dmBufferDDF.StreamDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dmBufferDDF.StreamDesc.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_type', full_name='dmBufferDDF.StreamDesc.value_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_count', full_name='dmBufferDDF.StreamDesc.value_count', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ui', full_name='dmBufferDDF.StreamDesc.ui', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='dmBufferDDF.StreamDesc.i', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ui64', full_name='dmBufferDDF.StreamDesc.ui64', index=5,
      number=6, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i64', full_name='dmBufferDDF.StreamDesc.i64', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='dmBufferDDF.StreamDesc.f', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name_hash', full_name='dmBufferDDF.StreamDesc.name_hash', index=8,
      number=9, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=243,
)


_BUFFERDESC = _descriptor.Descriptor(
  name='BufferDesc',
  full_name='dmBufferDDF.BufferDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='streams', full_name='dmBufferDDF.BufferDesc.streams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=299,
)

_STREAMDESC.fields_by_name['value_type'].enum_type = _VALUETYPE
_BUFFERDESC.fields_by_name['streams'].message_type = _STREAMDESC
DESCRIPTOR.message_types_by_name['StreamDesc'] = _STREAMDESC
DESCRIPTOR.message_types_by_name['BufferDesc'] = _BUFFERDESC
DESCRIPTOR.enum_types_by_name['ValueType'] = _VALUETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamDesc = _reflection.GeneratedProtocolMessageType('StreamDesc', (_message.Message,), dict(
  DESCRIPTOR = _STREAMDESC,
  __module__ = 'buffer_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmBufferDDF.StreamDesc)
  ))
_sym_db.RegisterMessage(StreamDesc)

BufferDesc = _reflection.GeneratedProtocolMessageType('BufferDesc', (_message.Message,), dict(
  DESCRIPTOR = _BUFFERDESC,
  __module__ = 'buffer_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmBufferDDF.BufferDesc)
  ))
_sym_db.RegisterMessage(BufferDesc)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
