# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ddf_script.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ddf_extensions_pb2 as ddf__extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ddf_script.proto',
  package='dmScriptDDF',
  syntax='proto2',
  serialized_options=_b('\n\032com.dynamo.ddfscript.protoB\tDdfScript'),
  serialized_pb=_b('\n\x10\x64\x64\x66_script.proto\x12\x0b\x64mScriptDDF\x1a\x14\x64\x64\x66_extensions.proto\"6\n\x06LuaRef\x12\x0e\n\x03ref\x18\x01 \x02(\x05:\x01\x30\x12\x1c\n\x11\x63ontext_table_ref\x18\x02 \x02(\x05:\x01\x30\x42\'\n\x1a\x63om.dynamo.ddfscript.protoB\tDdfScript')
  ,
  dependencies=[ddf__extensions__pb2.DESCRIPTOR,])




_LUAREF = _descriptor.Descriptor(
  name='LuaRef',
  full_name='dmScriptDDF.LuaRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref', full_name='dmScriptDDF.LuaRef.ref', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context_table_ref', full_name='dmScriptDDF.LuaRef.context_table_ref', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['LuaRef'] = _LUAREF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LuaRef = _reflection.GeneratedProtocolMessageType('LuaRef', (_message.Message,), dict(
  DESCRIPTOR = _LUAREF,
  __module__ = 'ddf_script_pb2'
  # @@protoc_insertion_point(class_scope:dmScriptDDF.LuaRef)
  ))
_sym_db.RegisterMessage(LuaRef)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
