# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ddf_extensions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ddf_extensions.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\020com.dynamo.protoB\rDdfExtensions'),
  serialized_pb=_b('\n\x14\x64\x64\x66_extensions.proto\x1a google/protobuf/descriptor.proto:0\n\x05\x61lias\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\t:7\n\x0cstruct_align\x12\x1f.google.protobuf.MessageOptions\x18\xd3\x86\x03 \x01(\x08:1\n\x08resource\x12\x1d.google.protobuf.FieldOptions\x18\xb4\x87\x03 \x01(\x08:4\n\x0b\x66ield_align\x12\x1d.google.protobuf.FieldOptions\x18\xd4\x86\x03 \x01(\x08:8\n\x0b\x64isplayName\x12!.google.protobuf.EnumValueOptions\x18\x98\x88\x03 \x01(\t:5\n\rddf_namespace\x12\x1c.google.protobuf.FileOptions\x18\xd1\x86\x03 \x01(\t:4\n\x0c\x64\x64\x66_includes\x12\x1c.google.protobuf.FileOptions\x18\xd2\x86\x03 \x01(\tB!\n\x10\x63om.dynamo.protoB\rDdfExtensions')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


ALIAS_FIELD_NUMBER = 50000
alias = _descriptor.FieldDescriptor(
  name='alias', full_name='alias', index=0,
  number=50000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
STRUCT_ALIGN_FIELD_NUMBER = 50003
struct_align = _descriptor.FieldDescriptor(
  name='struct_align', full_name='struct_align', index=1,
  number=50003, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RESOURCE_FIELD_NUMBER = 50100
resource = _descriptor.FieldDescriptor(
  name='resource', full_name='resource', index=2,
  number=50100, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
FIELD_ALIGN_FIELD_NUMBER = 50004
field_align = _descriptor.FieldDescriptor(
  name='field_align', full_name='field_align', index=3,
  number=50004, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DISPLAYNAME_FIELD_NUMBER = 50200
displayName = _descriptor.FieldDescriptor(
  name='displayName', full_name='displayName', index=4,
  number=50200, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DDF_NAMESPACE_FIELD_NUMBER = 50001
ddf_namespace = _descriptor.FieldDescriptor(
  name='ddf_namespace', full_name='ddf_namespace', index=5,
  number=50001, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
DDF_INCLUDES_FIELD_NUMBER = 50002
ddf_includes = _descriptor.FieldDescriptor(
  name='ddf_includes', full_name='ddf_includes', index=6,
  number=50002, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['alias'] = alias
DESCRIPTOR.extensions_by_name['struct_align'] = struct_align
DESCRIPTOR.extensions_by_name['resource'] = resource
DESCRIPTOR.extensions_by_name['field_align'] = field_align
DESCRIPTOR.extensions_by_name['displayName'] = displayName
DESCRIPTOR.extensions_by_name['ddf_namespace'] = ddf_namespace
DESCRIPTOR.extensions_by_name['ddf_includes'] = ddf_includes
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(alias)
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(struct_align)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(resource)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(field_align)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(displayName)
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(ddf_namespace)
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(ddf_includes)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
