# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http_ddf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ddf_extensions_pb2 as ddf__extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='http_ddf.proto',
  package='dmHttpDDF',
  syntax='proto2',
  serialized_options=_b('\n\017com.dynamo.httpB\tHttpProto'),
  serialized_pb=_b('\n\x0ehttp_ddf.proto\x12\tdmHttpDDF\x1a\x14\x64\x64\x66_extensions.proto\"\n\n\x08StopHttp\"\xd1\x01\n\x0bHttpRequest\x12\x0e\n\x06method\x18\x01 \x02(\t\x12\x0b\n\x03url\x18\x02 \x02(\t\x12\x0f\n\x07headers\x18\x03 \x02(\x04\x12\x16\n\x0eheaders_length\x18\x04 \x02(\x04\x12\x0f\n\x07request\x18\x05 \x02(\x04\x12\x16\n\x0erequest_length\x18\x06 \x02(\r\x12\x0f\n\x07timeout\x18\x07 \x01(\x04\x12\x0c\n\x04path\x18\x08 \x01(\t\x12\x14\n\x0cignore_cache\x18\t \x01(\x08\x12\x1e\n\x10\x63hunked_transfer\x18\n \x01(\x08:\x04true\"\x80\x01\n\x0cHttpResponse\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x0f\n\x07headers\x18\x02 \x02(\x04\x12\x16\n\x0eheaders_length\x18\x03 \x02(\r\x12\x10\n\x08response\x18\x04 \x02(\x04\x12\x17\n\x0fresponse_length\x18\x05 \x02(\r\x12\x0c\n\x04path\x18\x06 \x02(\tB\x1c\n\x0f\x63om.dynamo.httpB\tHttpProto')
  ,
  dependencies=[ddf__extensions__pb2.DESCRIPTOR,])




_STOPHTTP = _descriptor.Descriptor(
  name='StopHttp',
  full_name='dmHttpDDF.StopHttp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=61,
)


_HTTPREQUEST = _descriptor.Descriptor(
  name='HttpRequest',
  full_name='dmHttpDDF.HttpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='dmHttpDDF.HttpRequest.method', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='dmHttpDDF.HttpRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='dmHttpDDF.HttpRequest.headers', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers_length', full_name='dmHttpDDF.HttpRequest.headers_length', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='dmHttpDDF.HttpRequest.request', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_length', full_name='dmHttpDDF.HttpRequest.request_length', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='dmHttpDDF.HttpRequest.timeout', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='dmHttpDDF.HttpRequest.path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ignore_cache', full_name='dmHttpDDF.HttpRequest.ignore_cache', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunked_transfer', full_name='dmHttpDDF.HttpRequest.chunked_transfer', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=273,
)


_HTTPRESPONSE = _descriptor.Descriptor(
  name='HttpResponse',
  full_name='dmHttpDDF.HttpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dmHttpDDF.HttpResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='dmHttpDDF.HttpResponse.headers', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers_length', full_name='dmHttpDDF.HttpResponse.headers_length', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='dmHttpDDF.HttpResponse.response', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_length', full_name='dmHttpDDF.HttpResponse.response_length', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='dmHttpDDF.HttpResponse.path', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=404,
)

DESCRIPTOR.message_types_by_name['StopHttp'] = _STOPHTTP
DESCRIPTOR.message_types_by_name['HttpRequest'] = _HTTPREQUEST
DESCRIPTOR.message_types_by_name['HttpResponse'] = _HTTPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopHttp = _reflection.GeneratedProtocolMessageType('StopHttp', (_message.Message,), dict(
  DESCRIPTOR = _STOPHTTP,
  __module__ = 'http_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmHttpDDF.StopHttp)
  ))
_sym_db.RegisterMessage(StopHttp)

HttpRequest = _reflection.GeneratedProtocolMessageType('HttpRequest', (_message.Message,), dict(
  DESCRIPTOR = _HTTPREQUEST,
  __module__ = 'http_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmHttpDDF.HttpRequest)
  ))
_sym_db.RegisterMessage(HttpRequest)

HttpResponse = _reflection.GeneratedProtocolMessageType('HttpResponse', (_message.Message,), dict(
  DESCRIPTOR = _HTTPRESPONSE,
  __module__ = 'http_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmHttpDDF.HttpResponse)
  ))
_sym_db.RegisterMessage(HttpResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
