# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lua_source_ddf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lua_source_ddf.proto',
  package='dmLuaDDF',
  syntax='proto2',
  serialized_options=_b('\n\027com.dynamo.script.protoB\003Lua'),
  serialized_pb=_b('\n\x14lua_source_ddf.proto\x12\x08\x64mLuaDDF\"x\n\tLuaSource\x12\x0e\n\x06script\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x02(\t\x12\x10\n\x08\x62ytecode\x18\x03 \x01(\x0c\x12\r\n\x05\x64\x65lta\x18\x05 \x01(\x0c\x12\x13\n\x0b\x62ytecode_32\x18\x06 \x01(\x0c\x12\x13\n\x0b\x62ytecode_64\x18\x04 \x01(\x0c\x42\x1e\n\x17\x63om.dynamo.script.protoB\x03Lua')
)




_LUASOURCE = _descriptor.Descriptor(
  name='LuaSource',
  full_name='dmLuaDDF.LuaSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='script', full_name='dmLuaDDF.LuaSource.script', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='dmLuaDDF.LuaSource.filename', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytecode', full_name='dmLuaDDF.LuaSource.bytecode', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta', full_name='dmLuaDDF.LuaSource.delta', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytecode_32', full_name='dmLuaDDF.LuaSource.bytecode_32', index=4,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytecode_64', full_name='dmLuaDDF.LuaSource.bytecode_64', index=5,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['LuaSource'] = _LUASOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LuaSource = _reflection.GeneratedProtocolMessageType('LuaSource', (_message.Message,), dict(
  DESCRIPTOR = _LUASOURCE,
  __module__ = 'lua_source_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmLuaDDF.LuaSource)
  ))
_sym_db.RegisterMessage(LuaSource)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
