# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lua_ddf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ddf_extensions_pb2 as ddf__extensions__pb2
import ddf_math_pb2 as ddf__math__pb2
import lua_source_ddf_pb2 as lua__source__ddf__pb2
import properties_ddf_pb2 as properties__ddf__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lua_ddf.proto',
  package='dmLuaDDF',
  syntax='proto2',
  serialized_options=_b('\n\024com.dynamo.lua.protoB\003Lua'),
  serialized_pb=_b('\n\rlua_ddf.proto\x12\x08\x64mLuaDDF\x1a\x14\x64\x64\x66_extensions.proto\x1a\x0e\x64\x64\x66_math.proto\x1a\x14lua_source_ddf.proto\x1a\x14properties_ddf.proto\"\xb7\x01\n\tLuaModule\x12#\n\x06source\x18\x01 \x02(\x0b\x32\x13.dmLuaDDF.LuaSource\x12\x0f\n\x07modules\x18\x02 \x03(\t\x12\x17\n\tresources\x18\x03 \x03(\tB\x04\xa0\xbb\x18\x01\x12\x39\n\nproperties\x18\x04 \x01(\x0b\x32%.dmPropertiesDDF.PropertyDeclarations\x12 \n\x12property_resources\x18\x05 \x03(\tB\x04\xa0\xbb\x18\x01\x42\x1b\n\x14\x63om.dynamo.lua.protoB\x03Lua')
  ,
  dependencies=[ddf__extensions__pb2.DESCRIPTOR,ddf__math__pb2.DESCRIPTOR,lua__source__ddf__pb2.DESCRIPTOR,properties__ddf__pb2.DESCRIPTOR,])




_LUAMODULE = _descriptor.Descriptor(
  name='LuaModule',
  full_name='dmLuaDDF.LuaModule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='dmLuaDDF.LuaModule.source', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modules', full_name='dmLuaDDF.LuaModule.modules', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resources', full_name='dmLuaDDF.LuaModule.resources', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='dmLuaDDF.LuaModule.properties', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='property_resources', full_name='dmLuaDDF.LuaModule.property_resources', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=293,
)

_LUAMODULE.fields_by_name['source'].message_type = lua__source__ddf__pb2._LUASOURCE
_LUAMODULE.fields_by_name['properties'].message_type = properties__ddf__pb2._PROPERTYDECLARATIONS
DESCRIPTOR.message_types_by_name['LuaModule'] = _LUAMODULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LuaModule = _reflection.GeneratedProtocolMessageType('LuaModule', (_message.Message,), dict(
  DESCRIPTOR = _LUAMODULE,
  __module__ = 'lua_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmLuaDDF.LuaModule)
  ))
_sym_db.RegisterMessage(LuaModule)


DESCRIPTOR._options = None
_LUAMODULE.fields_by_name['resources']._options = None
_LUAMODULE.fields_by_name['property_resources']._options = None
# @@protoc_insertion_point(module_scope)
