# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_ddf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ddf_extensions_pb2 as ddf__extensions__pb2
import ddf_math_pb2 as ddf__math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_ddf.proto',
  package='dmModelDDF',
  syntax='proto2',
  serialized_options=_b('\n\030com.dynamo.gamesys.protoB\nModelProto'),
  serialized_pb=_b('\n\x0fmodel_ddf.proto\x12\ndmModelDDF\x1a\x14\x64\x64\x66_extensions.proto\x1a\x0e\x64\x64\x66_math.proto\"1\n\x07Texture\x12\x0f\n\x07sampler\x18\x01 \x02(\t\x12\x15\n\x07texture\x18\x02 \x02(\tB\x04\xa0\xbb\x18\x01\"W\n\x08Material\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x16\n\x08material\x18\x02 \x02(\tB\x04\xa0\xbb\x18\x01\x12%\n\x08textures\x18\x03 \x03(\x0b\x32\x13.dmModelDDF.Texture\"\xd3\x01\n\tModelDesc\x12\x12\n\x04mesh\x18\x02 \x02(\tB\x04\xa0\xbb\x18\x01\x12\x16\n\x08material\x18\x03 \x01(\tB\x04\xa0\xbb\x18\x01\x12\x16\n\x08textures\x18\x04 \x03(\tB\x04\xa0\xbb\x18\x01\x12\x16\n\x08skeleton\x18\x05 \x01(\tB\x04\xa0\xbb\x18\x01\x12\x18\n\nanimations\x18\x06 \x01(\tB\x04\xa0\xbb\x18\x01\x12\x19\n\x11\x64\x65\x66\x61ult_animation\x18\x07 \x01(\t\x12\x0c\n\x04name\x18\n \x01(\t\x12\'\n\tmaterials\x18\x0b \x03(\x0b\x32\x14.dmModelDDF.Material\"d\n\x05Model\x12\x17\n\trig_scene\x18\x01 \x02(\tB\x04\xa0\xbb\x18\x01\x12\x19\n\x11\x64\x65\x66\x61ult_animation\x18\x02 \x01(\t\x12\'\n\tmaterials\x18\x03 \x03(\x0b\x32\x14.dmModelDDF.Material\"\"\n\rResetConstant\x12\x11\n\tname_hash\x18\x01 \x02(\x04\"8\n\nSetTexture\x12\x14\n\x0ctexture_hash\x18\x01 \x02(\x04\x12\x14\n\x0ctexture_unit\x18\x02 \x02(\r\"\x84\x01\n\x12ModelPlayAnimation\x12\x14\n\x0c\x61nimation_id\x18\x01 \x02(\x04\x12\x10\n\x08playback\x18\x02 \x02(\r\x12\x19\n\x0e\x62lend_duration\x18\x03 \x01(\x02:\x01\x30\x12\x11\n\x06offset\x18\x04 \x01(\x02:\x01\x30\x12\x18\n\rplayback_rate\x18\x05 \x01(\x02:\x01\x31\"\x16\n\x14ModelCancelAnimation\"<\n\x12ModelAnimationDone\x12\x14\n\x0c\x61nimation_id\x18\x01 \x02(\x04\x12\x10\n\x08playback\x18\x02 \x02(\rB&\n\x18\x63om.dynamo.gamesys.protoB\nModelProto')
  ,
  dependencies=[ddf__extensions__pb2.DESCRIPTOR,ddf__math__pb2.DESCRIPTOR,])




_TEXTURE = _descriptor.Descriptor(
  name='Texture',
  full_name='dmModelDDF.Texture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sampler', full_name='dmModelDDF.Texture.sampler', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='texture', full_name='dmModelDDF.Texture.texture', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=118,
)


_MATERIAL = _descriptor.Descriptor(
  name='Material',
  full_name='dmModelDDF.Material',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dmModelDDF.Material.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='material', full_name='dmModelDDF.Material.material', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='textures', full_name='dmModelDDF.Material.textures', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=207,
)


_MODELDESC = _descriptor.Descriptor(
  name='ModelDesc',
  full_name='dmModelDDF.ModelDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mesh', full_name='dmModelDDF.ModelDesc.mesh', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='material', full_name='dmModelDDF.ModelDesc.material', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='textures', full_name='dmModelDDF.ModelDesc.textures', index=2,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skeleton', full_name='dmModelDDF.ModelDesc.skeleton', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='animations', full_name='dmModelDDF.ModelDesc.animations', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_animation', full_name='dmModelDDF.ModelDesc.default_animation', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='dmModelDDF.ModelDesc.name', index=6,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='materials', full_name='dmModelDDF.ModelDesc.materials', index=7,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=421,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='dmModelDDF.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rig_scene', full_name='dmModelDDF.Model.rig_scene', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\240\273\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_animation', full_name='dmModelDDF.Model.default_animation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='materials', full_name='dmModelDDF.Model.materials', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=523,
)


_RESETCONSTANT = _descriptor.Descriptor(
  name='ResetConstant',
  full_name='dmModelDDF.ResetConstant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name_hash', full_name='dmModelDDF.ResetConstant.name_hash', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=559,
)


_SETTEXTURE = _descriptor.Descriptor(
  name='SetTexture',
  full_name='dmModelDDF.SetTexture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='texture_hash', full_name='dmModelDDF.SetTexture.texture_hash', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='texture_unit', full_name='dmModelDDF.SetTexture.texture_unit', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=617,
)


_MODELPLAYANIMATION = _descriptor.Descriptor(
  name='ModelPlayAnimation',
  full_name='dmModelDDF.ModelPlayAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='animation_id', full_name='dmModelDDF.ModelPlayAnimation.animation_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playback', full_name='dmModelDDF.ModelPlayAnimation.playback', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blend_duration', full_name='dmModelDDF.ModelPlayAnimation.blend_duration', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='dmModelDDF.ModelPlayAnimation.offset', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playback_rate', full_name='dmModelDDF.ModelPlayAnimation.playback_rate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=752,
)


_MODELCANCELANIMATION = _descriptor.Descriptor(
  name='ModelCancelAnimation',
  full_name='dmModelDDF.ModelCancelAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=754,
  serialized_end=776,
)


_MODELANIMATIONDONE = _descriptor.Descriptor(
  name='ModelAnimationDone',
  full_name='dmModelDDF.ModelAnimationDone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='animation_id', full_name='dmModelDDF.ModelAnimationDone.animation_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playback', full_name='dmModelDDF.ModelAnimationDone.playback', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=778,
  serialized_end=838,
)

_MATERIAL.fields_by_name['textures'].message_type = _TEXTURE
_MODELDESC.fields_by_name['materials'].message_type = _MATERIAL
_MODEL.fields_by_name['materials'].message_type = _MATERIAL
DESCRIPTOR.message_types_by_name['Texture'] = _TEXTURE
DESCRIPTOR.message_types_by_name['Material'] = _MATERIAL
DESCRIPTOR.message_types_by_name['ModelDesc'] = _MODELDESC
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['ResetConstant'] = _RESETCONSTANT
DESCRIPTOR.message_types_by_name['SetTexture'] = _SETTEXTURE
DESCRIPTOR.message_types_by_name['ModelPlayAnimation'] = _MODELPLAYANIMATION
DESCRIPTOR.message_types_by_name['ModelCancelAnimation'] = _MODELCANCELANIMATION
DESCRIPTOR.message_types_by_name['ModelAnimationDone'] = _MODELANIMATIONDONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Texture = _reflection.GeneratedProtocolMessageType('Texture', (_message.Message,), dict(
  DESCRIPTOR = _TEXTURE,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.Texture)
  ))
_sym_db.RegisterMessage(Texture)

Material = _reflection.GeneratedProtocolMessageType('Material', (_message.Message,), dict(
  DESCRIPTOR = _MATERIAL,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.Material)
  ))
_sym_db.RegisterMessage(Material)

ModelDesc = _reflection.GeneratedProtocolMessageType('ModelDesc', (_message.Message,), dict(
  DESCRIPTOR = _MODELDESC,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.ModelDesc)
  ))
_sym_db.RegisterMessage(ModelDesc)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.Model)
  ))
_sym_db.RegisterMessage(Model)

ResetConstant = _reflection.GeneratedProtocolMessageType('ResetConstant', (_message.Message,), dict(
  DESCRIPTOR = _RESETCONSTANT,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.ResetConstant)
  ))
_sym_db.RegisterMessage(ResetConstant)

SetTexture = _reflection.GeneratedProtocolMessageType('SetTexture', (_message.Message,), dict(
  DESCRIPTOR = _SETTEXTURE,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.SetTexture)
  ))
_sym_db.RegisterMessage(SetTexture)

ModelPlayAnimation = _reflection.GeneratedProtocolMessageType('ModelPlayAnimation', (_message.Message,), dict(
  DESCRIPTOR = _MODELPLAYANIMATION,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.ModelPlayAnimation)
  ))
_sym_db.RegisterMessage(ModelPlayAnimation)

ModelCancelAnimation = _reflection.GeneratedProtocolMessageType('ModelCancelAnimation', (_message.Message,), dict(
  DESCRIPTOR = _MODELCANCELANIMATION,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.ModelCancelAnimation)
  ))
_sym_db.RegisterMessage(ModelCancelAnimation)

ModelAnimationDone = _reflection.GeneratedProtocolMessageType('ModelAnimationDone', (_message.Message,), dict(
  DESCRIPTOR = _MODELANIMATIONDONE,
  __module__ = 'model_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmModelDDF.ModelAnimationDone)
  ))
_sym_db.RegisterMessage(ModelAnimationDone)


DESCRIPTOR._options = None
_TEXTURE.fields_by_name['texture']._options = None
_MATERIAL.fields_by_name['material']._options = None
_MODELDESC.fields_by_name['mesh']._options = None
_MODELDESC.fields_by_name['material']._options = None
_MODELDESC.fields_by_name['textures']._options = None
_MODELDESC.fields_by_name['skeleton']._options = None
_MODELDESC.fields_by_name['animations']._options = None
_MODEL.fields_by_name['rig_scene']._options = None
# @@protoc_insertion_point(module_scope)
