# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: properties_ddf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ddf_extensions_pb2 as ddf__extensions__pb2
import ddf_math_pb2 as ddf__math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='properties_ddf.proto',
  package='dmPropertiesDDF',
  syntax='proto2',
  serialized_options=_b('\n\033com.dynamo.properties.protoB\017PropertiesProto'),
  serialized_pb=_b('\n\x14properties_ddf.proto\x12\x0f\x64mPropertiesDDF\x1a\x14\x64\x64\x66_extensions.proto\x1a\x0e\x64\x64\x66_math.proto\"W\n\x18PropertyDeclarationEntry\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x04\x12\r\n\x05index\x18\x03 \x02(\r\x12\x13\n\x0b\x65lement_ids\x18\x04 \x03(\x04\"\xa6\x04\n\x14PropertyDeclarations\x12\x41\n\x0enumber_entries\x18\x01 \x03(\x0b\x32).dmPropertiesDDF.PropertyDeclarationEntry\x12?\n\x0chash_entries\x18\x02 \x03(\x0b\x32).dmPropertiesDDF.PropertyDeclarationEntry\x12>\n\x0burl_entries\x18\x03 \x03(\x0b\x32).dmPropertiesDDF.PropertyDeclarationEntry\x12\x42\n\x0fvector3_entries\x18\x04 \x03(\x0b\x32).dmPropertiesDDF.PropertyDeclarationEntry\x12\x42\n\x0fvector4_entries\x18\x05 \x03(\x0b\x32).dmPropertiesDDF.PropertyDeclarationEntry\x12?\n\x0cquat_entries\x18\x06 \x03(\x0b\x32).dmPropertiesDDF.PropertyDeclarationEntry\x12?\n\x0c\x62ool_entries\x18\x07 \x03(\x0b\x32).dmPropertiesDDF.PropertyDeclarationEntry\x12\x14\n\x0c\x66loat_values\x18\x08 \x03(\x02\x12\x13\n\x0bhash_values\x18\t \x03(\x04\x12\x15\n\rstring_values\x18\n \x03(\tB.\n\x1b\x63om.dynamo.properties.protoB\x0fPropertiesProto')
  ,
  dependencies=[ddf__extensions__pb2.DESCRIPTOR,ddf__math__pb2.DESCRIPTOR,])




_PROPERTYDECLARATIONENTRY = _descriptor.Descriptor(
  name='PropertyDeclarationEntry',
  full_name='dmPropertiesDDF.PropertyDeclarationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dmPropertiesDDF.PropertyDeclarationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='dmPropertiesDDF.PropertyDeclarationEntry.id', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='dmPropertiesDDF.PropertyDeclarationEntry.index', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='element_ids', full_name='dmPropertiesDDF.PropertyDeclarationEntry.element_ids', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=166,
)


_PROPERTYDECLARATIONS = _descriptor.Descriptor(
  name='PropertyDeclarations',
  full_name='dmPropertiesDDF.PropertyDeclarations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_entries', full_name='dmPropertiesDDF.PropertyDeclarations.number_entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_entries', full_name='dmPropertiesDDF.PropertyDeclarations.hash_entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url_entries', full_name='dmPropertiesDDF.PropertyDeclarations.url_entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector3_entries', full_name='dmPropertiesDDF.PropertyDeclarations.vector3_entries', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector4_entries', full_name='dmPropertiesDDF.PropertyDeclarations.vector4_entries', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quat_entries', full_name='dmPropertiesDDF.PropertyDeclarations.quat_entries', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_entries', full_name='dmPropertiesDDF.PropertyDeclarations.bool_entries', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_values', full_name='dmPropertiesDDF.PropertyDeclarations.float_values', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_values', full_name='dmPropertiesDDF.PropertyDeclarations.hash_values', index=8,
      number=9, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_values', full_name='dmPropertiesDDF.PropertyDeclarations.string_values', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=719,
)

_PROPERTYDECLARATIONS.fields_by_name['number_entries'].message_type = _PROPERTYDECLARATIONENTRY
_PROPERTYDECLARATIONS.fields_by_name['hash_entries'].message_type = _PROPERTYDECLARATIONENTRY
_PROPERTYDECLARATIONS.fields_by_name['url_entries'].message_type = _PROPERTYDECLARATIONENTRY
_PROPERTYDECLARATIONS.fields_by_name['vector3_entries'].message_type = _PROPERTYDECLARATIONENTRY
_PROPERTYDECLARATIONS.fields_by_name['vector4_entries'].message_type = _PROPERTYDECLARATIONENTRY
_PROPERTYDECLARATIONS.fields_by_name['quat_entries'].message_type = _PROPERTYDECLARATIONENTRY
_PROPERTYDECLARATIONS.fields_by_name['bool_entries'].message_type = _PROPERTYDECLARATIONENTRY
DESCRIPTOR.message_types_by_name['PropertyDeclarationEntry'] = _PROPERTYDECLARATIONENTRY
DESCRIPTOR.message_types_by_name['PropertyDeclarations'] = _PROPERTYDECLARATIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropertyDeclarationEntry = _reflection.GeneratedProtocolMessageType('PropertyDeclarationEntry', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTYDECLARATIONENTRY,
  __module__ = 'properties_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmPropertiesDDF.PropertyDeclarationEntry)
  ))
_sym_db.RegisterMessage(PropertyDeclarationEntry)

PropertyDeclarations = _reflection.GeneratedProtocolMessageType('PropertyDeclarations', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTYDECLARATIONS,
  __module__ = 'properties_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmPropertiesDDF.PropertyDeclarations)
  ))
_sym_db.RegisterMessage(PropertyDeclarations)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
