# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_ddf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ddf_extensions_pb2 as ddf__extensions__pb2
import ddf_math_pb2 as ddf__math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='resource_ddf.proto',
  package='dmResourceDDF',
  syntax='proto2',
  serialized_options=_b('\n\031com.dynamo.resource.protoB\010Resource'),
  serialized_pb=_b('\n\x12resource_ddf.proto\x12\rdmResourceDDF\x1a\x14\x64\x64\x66_extensions.proto\x1a\x0e\x64\x64\x66_math.proto\"\x1b\n\x06Reload\x12\x11\n\tresources\x18\x01 \x03(\tB%\n\x19\x63om.dynamo.resource.protoB\x08Resource')
  ,
  dependencies=[ddf__extensions__pb2.DESCRIPTOR,ddf__math__pb2.DESCRIPTOR,])




_RELOAD = _descriptor.Descriptor(
  name='Reload',
  full_name='dmResourceDDF.Reload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resources', full_name='dmResourceDDF.Reload.resources', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['Reload'] = _RELOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reload = _reflection.GeneratedProtocolMessageType('Reload', (_message.Message,), dict(
  DESCRIPTOR = _RELOAD,
  __module__ = 'resource_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmResourceDDF.Reload)
  ))
_sym_db.RegisterMessage(Reload)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
